# $FreeBSD: head/en_US.ISO8859-1/htdocs/ports/growth/Makefile 38826 2012-05-17 19:12:14Z hrs $
#

TOOLDIR=${.CURDIR}/../../../../share/tools/portsgrowth

all install clean:
	cd ${TOOLDIR}; \
		 ${MAKE} ${MAKEFLAGS} ${.TARGETS}

