# $FreeBSD: head/en_US.ISO8859-1/htdocs/layout/js/Makefile 39627 2012-09-30 13:27:05Z issyl0 $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   google.js

.include "${DOC_PREFIX}/share/mk/web.site.mk"
