# $FreeBSD: head/en_US.ISO8859-1/htdocs/advocacy/Makefile 39631 2012-10-01 09:53:01Z gabor $
#
# Makefile for the advocacy site

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.xml
DOCS+=	myths.xml
DOCS+=	whyusefreebsd.xml
.include "${DOC_PREFIX}/share/mk/web.site.mk"
