# $FreeBSD: head/en_US.ISO8859-1/htdocs/community/Makefile 42980 2013-10-17 04:33:22Z eadler $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.xml mailinglists.xml newsgroups.xml webresources.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
