# $FreeBSD: head/en_US.ISO8859-1/htdocs/releases/1.0/Makefile 45901 2014-11-01 20:51:25Z gavin $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
