# $FreeBSD: head/en_US.ISO8859-1/htdocs/releases/1.1/Makefile 38826 2012-05-17 19:12:14Z hrs $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	CONTRIB.386BSD CONTRIB.FreeBSD COPYRIGHT.386BSD COPYRIGHT.FreeBSD
DATA+=	MIRROR.SITES PERSONAL.ACKS RELNOTES.FreeBSD SUPPORT.TXT

.include "${DOC_PREFIX}/share/mk/web.site.mk"
