# ACPI project page
#
# $FreeBSD: head/en_US.ISO8859-1/htdocs/projects/acpi/Makefile 39631 2012-10-01 09:53:01Z gabor $

MAINTAINER=	marks

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.xml
DOCS+=	completed.xml
DATA=	style.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
