# $FreeBSD: head/en_US.ISO8859-1/htdocs/docproj/Makefile 46615 2015-04-27 02:06:14Z eadler $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   current.xml
DOCS+=	doc-set.xml
DOCS+=  submitting.xml
DOCS+=  who.xml
DOCS+=  translations.xml
DOCS+=	docproj.xml

INDEXLINK= docproj.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
