#
# Build the Porters Handbook with just the content from this chapter.
#
# $FreeBSD: head/en_US.ISO8859-1/books/porters-handbook/porting-dads/Makefile 43840 2014-02-09 01:50:53Z trhodes $
#

CHAPTERS= 	porting-dads/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
