#
# $FreeBSD: head/en_US.ISO8859-1/articles/cups/Makefile 39631 2012-10-01 09:53:01Z gabor $
#
# Article: CUPS on FreeBSD

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
