#
# $FreeBSD: head/en_US.ISO8859-1/articles/ldap-auth/Makefile 39631 2012-10-01 09:53:01Z gabor $
#
# Article: LDAP Authentication

MAINTAINER= kurin@causa-sui.net

DOC?=	article

FORMATS?= html-split html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
