# $FreeBSD: head/en_US.ISO8859-1/htdocs/releases/9.3R/Makefile 45300 2014-07-15 16:28:10Z gjb $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.xml \
	schedule.xml \
	todo.xml

DATA=	announce.asc \
	docbook.css \
	errata.html \
	hardware.html \
	installation.html \
	readme.html \
	relnotes.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
