#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: head/en_US.ISO8859-1/books/handbook/jails/Makefile 39829 2012-10-28 22:23:29Z gjb $
#

CHAPTERS=	jails/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?=	${.CURDIR}/../../../..

.include "../Makefile"
