# $FreeBSD: head/en_US.ISO8859-1/htdocs/releases/9.2R/Makefile 42775 2013-09-30 20:20:03Z gjb $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.xml \
	relnotes.xml \
	schedule.xml

DATA=	docbook.css \
	errata.html \
	hardware.html \
	installation.html \
	readme.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
