#
# $FreeBSD: head/en_US.ISO8859-1/articles/freebsd-questions/Makefile 39631 2012-10-01 09:53:01Z gabor $
#
# Article: How to get best results from the FreeBSD-questions mailing list

MAINTAINER=grog@FreeBSD.org

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
