# $FreeBSD: head/en_US.ISO8859-1/htdocs/layout/Makefile 39534 2012-09-14 12:11:19Z gabor $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=		css
SUBDIR+=	images
SUBDIR+=	js

.include "${DOC_PREFIX}/share/mk/web.site.mk"
