#
# $FreeBSD: head/en_US.ISO8859-1/articles/building-products/Makefile 39631 2012-10-01 09:53:01Z gabor $
#
# Article: Building products using FreeBSD

DOC?=			article

FORMATS?=		html

INSTALL_COMPRESSED?=	gz
INSTALL_ONLY_COMPRESSED?=

SRCS=			article.xml

IMAGES_EN=		freebsd-branches.pic freebsd-organization.pic

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
