# The FreeBSD Korean Documentation Project
# $FreeBSD: head/ko_KR.UTF-8/Makefile 47294 2015-08-21 13:44:39Z blackend $
# Original Revision: 1.7

SUBDIR = articles
#SUBDIR+= books

COMPAT_SYMLINK = ko

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
