# The FreeBSD Korean Documentation Project
#
# $FreeBSD: head/ko_KR.UTF-8/articles/bsdl-gpl/Makefile 39631 2012-10-01 09:53:01Z gabor $
#
# BSDL vs GPL article.
#
# Original Revision:

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
