# $FreeBSD: head/en_US.ISO8859-1/htdocs/news/2012-compromise/Makefile 40086 2012-11-18 22:49:29Z gavin $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=		md5.sums.20121118.txt
DATA+=		sha256.sums.20121118.txt

.include "${DOC_PREFIX}/share/mk/web.site.mk"
