# FreeBSD list of projects and ideas for volunteers
#
# $FreeBSD: head/en_US.ISO8859-1/htdocs/projects/ideas/Makefile 39631 2012-10-01 09:53:01Z gabor $

MAINTAINER=	joel

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	style.css

DOCS=	ideas.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
