#
# $FreeBSD: head/en_US.ISO8859-1/articles/gjournal-desktop/Makefile 39631 2012-10-01 09:53:01Z gabor $
#
# Article: Implementing UFS journaling on a desktop PC

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml
IMAGES_EN=	disklabel1.png
IMAGES_EN+=	disklabel2.png
URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
