# $FreeBSD: head/en_US.ISO8859-1/Makefile 38826 2012-05-17 19:12:14Z hrs $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = en

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
