# $FreeBSD: head/en_US.ISO8859-1/htdocs/layout/css/Makefile 46874 2015-06-27 02:36:16Z peter $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=
DATA+=	fixed.css
DATA+=	fixed_large.css
DATA+=	global.css
DATA+=	iefixes.css
DATA+=	layout.css
DATA+=	navigation.css
DATA+=	table.css
DATA+=	text.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
