# The FreeBSD Korean Documentation Project
# $FreeBSD: head/ko_KR.UTF-8/articles/Makefile 47294 2015-08-21 13:44:39Z blackend $
# Original Revision:

SUBDIR =
SUBDIR+= bsdl-gpl
SUBDIR+= contributing
SUBDIR+= explaining-bsd

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
