# The FreeBSD Korean Documentation Project
#
# $FreeBSD: head/ko_KR.UTF-8/articles/Makefile.inc 39534 2012-09-14 12:11:19Z gabor $
#
# Original Revision:

DESTDIR?=	${DOCDIR}/ko_KR.UTF-8/articles/${.CURDIR:T}
