# The FreeBSD Korean Documentation Project
#
# $FreeBSD: head/ko_KR.UTF-8/articles/Makefile.inc 47294 2015-08-21 13:44:39Z blackend $
#
# Original Revision:

DESTDIR?=	${DOCDIR}/ko_KR.UTF-8/articles/${.CURDIR:T}
