# $FreeBSD: head/en_US.ISO8859-1/htdocs/releases/11.0R/Makefile 47527 2015-10-09 15:41:29Z gjb $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.xml \
	schedule.xml \
	todo.xml

DATA=	docbook.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
