# $FreeBSD: head/en_US.ISO8859-1/htdocs/releases/11.0R/Makefile 46298 2015-02-26 21:57:14Z gjb $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.xml \
	todo.xml

DATA=	docbook.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
