#
# $FreeBSD: head/en_US.ISO8859-1/articles/solid-state/Makefile 39631 2012-10-01 09:53:01Z gabor $
#
# Article: FreeBSD and Solid State Devices

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
