# $FreeBSD: head/en_US.ISO8859-1/htdocs/donations/Makefile 43866 2014-02-11 03:07:20Z gjb $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.xml donors.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
