#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: head/en_US.ISO8859-1/books/handbook/x11/Makefile 39631 2012-10-01 09:53:01Z gabor $
#

CHAPTERS= 	x11/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
