# $FreeBSD: head/en_US.ISO8859-1/htdocs/releases/9.1R/Makefile 40515 2012-12-30 17:38:03Z hrs $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.xml \
	relnotes.xml \
	schedule.xml

DATA=	docbook.css \
	errata.html \
	hardware.html \
	readme.html \
	relnotes-detailed.html \
	installation.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
