#
# $FreeBSD: head/en_US.ISO8859-1/articles/fonts/Makefile 39631 2012-10-01 09:53:01Z gabor $
#
# Article: Fonts and FreeBSD

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
