# $FreeBSD: head/en_US.ISO8859-1/htdocs/releases/10.1R/Makefile 45983 2014-11-14 19:14:46Z gjb $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.xml \
	schedule.xml \
	todo.xml

DATA=	announce.asc \
	installation.html \
	docbook.css \
	errata.html \
	hardware.html \
	readme.html \
	relnotes.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
