#
# $FreeBSD: head/en_US.ISO8859-1/articles/leap-seconds/Makefile 46873 2015-06-27 00:25:33Z wblock $
#
# Article: Leap Seconds

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
