# $FreeBSD: head/en_US.ISO8859-1/htdocs/layout/images/Makefile 40576 2013-01-12 18:33:11Z gjb $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	beastie.png
DATA+=	blt_gry_arrow.png
DATA+=	blt_red_arrow.png
DATA+=	hdr_fill.png
DATA+=	ico_rss.png
DATA+=	logo.png
DATA+=	logo-red.png
DATA+=	nav_rgt.png
DATA+=	nav_tbl_btm.png
DATA+=	nav_tbl_top.png

.include "${DOC_PREFIX}/share/mk/web.site.mk"
